name: "\U0001F4AC General / Question"
description: Ask a question or start a discussion
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Your question
    validations:
      required: true
