//! Worldgen scheduler scaffolding.
//!
//! Tracks pending and in-progress chunk generation tasks, dispatching work
//! to a dedicated [`rayon::ThreadPool`] when neighbor dependencies are
//! satisfied.
//!
//! **This is scaffolding only.** The dispatch loop and actual generation
//! integration are implemented in feature phases (P23/P26/P36).

use std::sync::Arc;

use dashmap::DashMap;
use oxidized_types::ChunkPos;
use tokio::sync::Semaphore;
use tokio_util::sync::CancellationToken;

use super::ChunkStatus;
use super::priority::ChunkGenPriority;
use super::status_requirements;

/// Default maximum number of concurrently generating chunks.
///
/// Each in-progress chunk uses ~256 KB for noise caches and partial section
/// data. At 64 concurrent chunks this totals ~16 MB — acceptable for most
/// server configurations.
pub const DEFAULT_MAX_CONCURRENT: usize = 64;

/// Dependency-aware chunk generation scheduler.
///
/// Manages a queue of pending generation tasks, tracks which chunks are
/// currently being generated, and dispatches ready tasks to the Rayon
/// thread pool. The semaphore enforces a memory budget by limiting the
/// number of concurrent in-flight chunks.
///
/// # Scheduling algorithm (future phases)
///
/// 1. Collect all pending chunks whose dependencies are satisfied.
/// 2. Sort by priority (Urgent first).
/// 3. Submit up to `max_concurrent` tasks to the Rayon pool.
/// 4. On completion, update status and check if dependents are now ready.
pub struct WorldgenScheduler {
    /// Chunks waiting to be generated, keyed by position.
    pending: DashMap<ChunkPos, ChunkGenTask>,
    /// Chunks currently being generated by the Rayon pool.
    in_progress: DashMap<ChunkPos, ChunkStatus>,
    /// Dedicated thread pool for CPU-bound generation work.
    rayon_pool: rayon::ThreadPool,
    /// Maximum number of chunks generating simultaneously.
    max_concurrent: usize,
    /// Enforces the memory budget for concurrent generation.
    semaphore: Arc<Semaphore>,
}

/// A pending chunk generation task.
///
/// Tracks the target and current status, generation priority, and a
/// cancellation token for aborting work that is no longer needed (e.g.
/// when a player moves away).
#[derive(Debug, Clone)]
pub struct ChunkGenTask {
    /// The status this chunk should reach.
    pub target_status: ChunkStatus,
    /// The status this chunk has already reached.
    pub current_status: ChunkStatus,
    /// Scheduling priority — higher-priority tasks are dispatched first.
    pub priority: ChunkGenPriority,
    /// Token for cooperative cancellation of in-progress generation.
    pub cancel_token: CancellationToken,
}

impl WorldgenScheduler {
    /// Creates a new scheduler with the given concurrency limit.
    ///
    /// A dedicated Rayon thread pool is created for worldgen work, isolated
    /// from any global pool to avoid interference with other CPU-bound tasks.
    ///
    /// # Errors
    ///
    /// Returns an error if the Rayon thread pool cannot be created.
    pub fn new(max_concurrent: usize) -> Result<Self, rayon::ThreadPoolBuildError> {
        let rayon_pool = rayon::ThreadPoolBuilder::new()
            .thread_name(|index| format!("worldgen-{index}"))
            .build()?;

        Ok(Self {
            pending: DashMap::new(),
            in_progress: DashMap::new(),
            rayon_pool,
            max_concurrent,
            semaphore: Arc::new(Semaphore::new(max_concurrent)),
        })
    }

    /// Creates a scheduler with [`DEFAULT_MAX_CONCURRENT`] as the limit.
    ///
    /// # Errors
    ///
    /// Returns an error if the Rayon thread pool cannot be created.
    pub fn with_defaults() -> Result<Self, rayon::ThreadPoolBuildError> {
        Self::new(DEFAULT_MAX_CONCURRENT)
    }

    /// Enqueues a chunk for generation to the given target status.
    ///
    /// If a task for this position already exists, it is replaced only if
    /// the new task has a higher priority.
    pub fn enqueue(
        &self,
        pos: ChunkPos,
        target_status: ChunkStatus,
        current_status: ChunkStatus,
        priority: ChunkGenPriority,
    ) {
        let task = ChunkGenTask {
            target_status,
            current_status,
            priority,
            cancel_token: CancellationToken::new(),
        };

        self.pending
            .entry(pos)
            .and_modify(|existing| {
                if priority > existing.priority {
                    existing.cancel_token.cancel();
                    *existing = task.clone();
                }
            })
            .or_insert(task);
    }

    /// Cancels a pending generation task for the given chunk position.
    ///
    /// If the chunk is in the pending queue, its cancellation token is
    /// triggered and the task is removed. If the chunk is already being
    /// generated by the Rayon pool, only the token is cancelled — the
    /// worker will check the token at the next phase boundary.
    pub fn cancel(&self, pos: &ChunkPos) {
        if let Some((_, task)) = self.pending.remove(pos) {
            task.cancel_token.cancel();
        }
        // In-progress tasks check their token at phase boundaries.
    }

    /// Returns the number of chunks currently pending generation.
    #[must_use]
    pub fn pending_count(&self) -> usize {
        self.pending.len()
    }

    /// Returns the number of chunks currently being generated.
    #[must_use]
    pub fn in_progress_count(&self) -> usize {
        self.in_progress.len()
    }

    /// Returns the maximum concurrent generation limit.
    #[must_use]
    pub const fn max_concurrent(&self) -> usize {
        self.max_concurrent
    }

    /// Returns a reference to the dedicated Rayon thread pool.
    #[must_use]
    pub fn rayon_pool(&self) -> &rayon::ThreadPool {
        &self.rayon_pool
    }

    /// Returns a reference to the concurrency semaphore.
    ///
    /// The dispatch loop (future phases) acquires permits from this semaphore
    /// before submitting generation tasks to the Rayon pool.
    #[must_use]
    pub fn semaphore(&self) -> &Arc<Semaphore> {
        &self.semaphore
    }

    /// Checks whether all neighbor dependencies are satisfied for advancing
    /// the chunk at `pos` to `target_status`.
    ///
    /// Delegates to [`status_requirements::dependencies_satisfied`] using
    /// the provided chunk status lookup function. In the full implementation,
    /// this queries the world's chunk map.
    #[must_use]
    pub fn are_dependencies_satisfied(
        pos: ChunkPos,
        target_status: ChunkStatus,
        get_chunk_status: impl Fn(ChunkPos) -> Option<ChunkStatus>,
    ) -> bool {
        status_requirements::dependencies_satisfied(pos, target_status, get_chunk_status)
    }
}

impl ChunkGenTask {
    /// Creates a new generation task.
    #[must_use]
    pub fn new(
        target_status: ChunkStatus,
        current_status: ChunkStatus,
        priority: ChunkGenPriority,
    ) -> Self {
        Self {
            target_status,
            current_status,
            priority,
            cancel_token: CancellationToken::new(),
        }
    }

    /// Returns the next status this chunk should advance to.
    ///
    /// This is one step past `current_status` in the pipeline, capped at
    /// `target_status`.
    #[must_use]
    pub fn next_status(&self) -> Option<ChunkStatus> {
        let next = (self.current_status as u8).checked_add(1)?;
        let target = self.target_status as u8;
        if next > target {
            return None;
        }
        ChunkStatus::from_u8(next)
    }

    /// Returns `true` if this task has reached its target status.
    #[must_use]
    pub fn is_complete(&self) -> bool {
        self.current_status.is_or_after(self.target_status)
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;

    #[test]
    fn scheduler_creation() {
        let scheduler = WorldgenScheduler::new(32).unwrap();
        assert_eq!(scheduler.max_concurrent(), 32);
        assert_eq!(scheduler.pending_count(), 0);
        assert_eq!(scheduler.in_progress_count(), 0);
    }

    #[test]
    fn enqueue_and_cancel() {
        let scheduler = WorldgenScheduler::new(4).unwrap();
        let pos = ChunkPos::new(1, 2);

        scheduler.enqueue(
            pos,
            ChunkStatus::Full,
            ChunkStatus::Empty,
            ChunkGenPriority::Normal,
        );
        assert_eq!(scheduler.pending_count(), 1);

        scheduler.cancel(&pos);
        assert_eq!(scheduler.pending_count(), 0);
    }

    #[test]
    fn enqueue_replaces_lower_priority() {
        let scheduler = WorldgenScheduler::new(4).unwrap();
        let pos = ChunkPos::new(3, 4);

        scheduler.enqueue(
            pos,
            ChunkStatus::Full,
            ChunkStatus::Empty,
            ChunkGenPriority::Low,
        );

        scheduler.enqueue(
            pos,
            ChunkStatus::Full,
            ChunkStatus::Empty,
            ChunkGenPriority::Urgent,
        );

        assert_eq!(scheduler.pending_count(), 1);
        let entry = scheduler.pending.get(&pos).unwrap();
        assert_eq!(entry.priority, ChunkGenPriority::Urgent);
    }

    #[test]
    fn enqueue_keeps_higher_priority() {
        let scheduler = WorldgenScheduler::new(4).unwrap();
        let pos = ChunkPos::new(3, 4);

        scheduler.enqueue(
            pos,
            ChunkStatus::Full,
            ChunkStatus::Empty,
            ChunkGenPriority::Urgent,
        );

        scheduler.enqueue(
            pos,
            ChunkStatus::Full,
            ChunkStatus::Empty,
            ChunkGenPriority::Low,
        );

        let entry = scheduler.pending.get(&pos).unwrap();
        assert_eq!(entry.priority, ChunkGenPriority::Urgent);
    }

    #[test]
    fn task_next_status() {
        let task = ChunkGenTask::new(
            ChunkStatus::Noise,
            ChunkStatus::Empty,
            ChunkGenPriority::Normal,
        );
        assert_eq!(task.next_status(), Some(ChunkStatus::StructureStarts));
        assert!(!task.is_complete());
    }

    #[test]
    fn task_complete_when_at_target() {
        let task = ChunkGenTask::new(
            ChunkStatus::Full,
            ChunkStatus::Full,
            ChunkGenPriority::Normal,
        );
        assert!(task.is_complete());
        assert!(task.next_status().is_none());
    }

    #[test]
    fn dependencies_satisfied_with_mock_statuses() {
        // Features needs radius-1 neighbors at Carvers.
        let all_at_full = |_: ChunkPos| Some(ChunkStatus::Full);
        assert!(WorldgenScheduler::are_dependencies_satisfied(
            ChunkPos::new(0, 0),
            ChunkStatus::Features,
            all_at_full,
        ));

        // One neighbor missing → not satisfied.
        let one_missing = |pos: ChunkPos| {
            if pos == ChunkPos::new(1, 0) {
                Some(ChunkStatus::Noise) // below Carvers
            } else {
                Some(ChunkStatus::Full)
            }
        };
        assert!(!WorldgenScheduler::are_dependencies_satisfied(
            ChunkPos::new(0, 0),
            ChunkStatus::Features,
            one_missing,
        ));
    }

    #[test]
    fn dependencies_satisfied_no_requirement() {
        // Noise has radius 0 → always satisfied.
        let no_data = |_: ChunkPos| None;
        assert!(WorldgenScheduler::are_dependencies_satisfied(
            ChunkPos::new(0, 0),
            ChunkStatus::Noise,
            no_data,
        ));
    }
}
