name: Dev Publish

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: [main]

jobs:
  publish:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      !contains(github.event.workflow_run.head_commit.message, 'chore: release') &&
      !contains(github.event.workflow_run.head_commit.message, 'chore(release)')
    uses: oxidized-mc/ci/.github/workflows/cargo-publish-dev.yml@main
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

